version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: bedrock_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html/web
    depends_on:
      - wordpress

  wordpress:
    build: 
      context: .
      dockerfile: Dockerfile.php
    container_name: bedrock_wordpress
    environment:
      - DB_HOST=db
      - DB_USER=wordpress
      - DB_PASSWORD=wordpress
      - DB_NAME=wordpress
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./web:/var/www/html/web
      - ./config:/var/www/html/config
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    working_dir: /var/www/html

  composer:
    image: composer:latest
    container_name: bedrock_composer
    volumes:
      - .:/app
    working_dir: /app
    command: composer install

  db:
    image: mysql:8.0
    container_name: bedrock_mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    command: 
      - --default-authentication-plugin=mysql_native_password

  node:
    image: node:18
    container_name: sage_theme_node
    volumes:
      - ./web/app/themes/sage-demo:/app
    working_dir: /app
    command: npm install && npm run dev

volumes:
  db_data: {}